// --- 多语言排序变量 ---
const speedOrder_cn = ['充能', '魔法', '冥河', '飞速', '快速', '潮汐', '中等', '杀手', '慢', '非常慢'];
const speedOrder_tc = ['充能', '魔法', '冥河', '飛速', '快速', '潮汐', '中等', '殺手', '慢速', '非常慢'];
const speedOrder_en = ['Charge', 'Magic', 'Styx', 'Very Fast', 'Fast', 'Changing Tides', 'Average', 'Slayer', 'Slow', 'Very Slow'];
const colorOrder_cn = ['红', '绿', '蓝', '黄', '紫'];
const colorOrder_tc = ['紅', '綠', '藍', '黃', '紫'];
const colorOrder_en = ['Red', 'Green', 'Blue', 'Yellow', 'Purple'];

// Nynaeve 技能类型的英文排序标准
const nynaeveSkillTypeOrder = [
    'Snipers',
    'AoE Attackers (Hit-3)',
    'AoE Attackers (Hit-5)',
    'Chain & Random Attackers',
    'DoT Attackers',
    'Revivers',
    'Healers',
    'Health Boosters',
    'Heal over Time (HoT)',
    'Healers (Special)',
    'Dancers',
    'Mega Minions Summoners',
    'Minions Summoners',
    'Fiends Summoners',
    'Taunters',
    'Bypassers',
    'Healing Reducers',
    'Ability Scores Modifiers',
    'Negative Effects On Self Or Allies',
    'Board Alterers',
    'Buff Blockers',
    'Buff Stealers',
    'Buffers (ATK)',
    'Buffers (DEF)',
    'Cleanse Blockers',
    'Cleansers',
    'Counterattackers',
    'Damage Reducers',
    'Damage Sharers',
    'Debuffers (ATK)',
    'Debuffers (DEF)',
    'Dispellers',
    'Dodgers',
    'Effect Duration Resetters',
    'Extra Damage Dealers',
    'Fiends Counters',
    'Ghost Form & Hiding',
    'Immunity Providers',
    'Mana Corruption',
    'Mana Generation Buffers',
    'Mana Raisers',
    'Mana Reducers or Blockers',
    'Max Health Reducers',
    'Mindless Attack & Mindless Heal',
    'Minions Boosters',
    'Minions Counters',
    'Random Position',
    'Reflectors',
    'Resurrection Inhibitors',
    'Silencers',
    'Sleepweavers',
    'Stacking Heroes',
    'Status Effects Blockers',
    'Status Effect Conversion'
];

// --- 技能类型翻译映射表 ---
const skillTypeTranslations_cn = {
    "Buffers (ATK)": "攻击增益", "Buffers (DEF)": "防御增益", "Debuffers (ATK)": "攻击减益", "Debuffers (DEF)": "防御减益",
    "Stacks Removers": "叠加移除", "Stacking Heroes": "叠加", "Extra Damage Dealers": "额外伤害", "DoT Attackers": "持续伤害",
    "Dispellers": "驱散", "Cleansers": "净化", "Buff Stealers": "增益窃取者", "Buff Blockers": "增益格挡者",
    "Cleanse Blockers": "净化格挡者", "Status Effects Blockers": "状态效果格挡", "Effect Duration Resetters": "效果持续重置",
    "Dancers": "舞者", "Healers": "治疗", "Healers (Special)": "特殊治疗", "Heal over Time (HoT)": "持续治疗",
    "Health Boosters": "生命强化", "Max Health Reducers": "最大生命削减", "Healing Reducers": "治疗削减", "Revivers": "复活",
    "Resurrection Inhibitors": "复活抑制", "Random Position": "重排队伍", "Mana Raisers": "法力提升", "Mana Generation Buffers": "法力生成增益",
    "Mana Reducers or Blockers": "法力削减或格挡", "Mana Corruption": "法力腐败", "Mindless Attack & Mindless Heal": "精神错乱攻击&治疗",
    "Silencers": "沉默", "Sleepweavers": "沉睡", "Taunters": "嘲讽", "Damage Sharers": "伤害分摊", "Damage Reducers": "伤害减免",
    "Dodgers": "闪避", "Ghost Form & Hiding": "鬼魂形态与隐藏", "Immunity Providers": "提供免疫", "Minions Summoners": "召唤小兵",
    "Mega Minions Summoners": "召唤巨型小兵", "Minions Counters": "反制小兵", "Minions Boosters": "小兵强化", "Fiends Summoners": "召唤恶魔",
    "Fiends Counters": "反制恶魔", "Counterattackers": "反击", "Reflectors": "反射", "Bypassers": "绕过", "Targeting Type": "目标类型",
    "Snipers": "狙击手", "AoE Attackers (Hit-5)": "全体攻击 (打5)", "AoE Attackers (Hit-3)": "范围攻击 (打3)",
    "Chain & Random Attackers": "连锁与随机攻击", "Board Alterers": "改变面板", "Ability Scores Modifiers": "属性修改",
    "Negative Effects On Self Or Allies": "对自身或友军负面效果", "Status Effect Conversion": "状态效果转换"
};
const skillTypeTranslations_tc = {
    "Buffers (ATK)": "攻擊增益", "Buffers (DEF)": "防禦增益", "Debuffers (ATK)": "攻擊減益", "Debuffers (DEF)": "防禦減益",
    "Stacks Removers": "疊加移除", "Stacking Heroes": "疊加", "Extra Damage Dealers": "額外傷害", "DoT Attackers": "持續傷害",
    "Dispellers": "驅散", "Cleansers": "凈化", "Buff Stealers": "增益竊取者", "Buff Blockers": "增益格擋者",
    "Cleanse Blockers": "凈化格擋者", "Status Effects Blockers": "狀態效果格擋", "Effect Duration Resetters": "效果持續重置",
    "Dancers": "舞者", "Healers": "治療", "Healers (Special)": "特殊治療", "Heal over Time (HoT)": "持續治療",
    "Health Boosters": "生命強化", "Max Health Reducers": "最大生命削減", "Healing Reducers": "治療削減", "Revivers": "復活",
    "Resurrection Inhibitors": "復活抑製", "Random Position": "重排隊伍", "Mana Raisers": "法力提升", "Mana Generation Buffers": "法力生成增益",
    "Mana Reducers or Blockers": "法力削減或格擋", "Mana Corruption": "法力腐敗", "Mindless Attack & Mindless Heal": "精神錯亂攻擊&治療",
    "Silencers": "沈默", "Sleepweavers": "沈睡", "Taunters": "嘲諷", "Damage Sharers": "傷害分攤", "Damage Reducers": "傷害減免",
    "Dodgers": "閃避", "Ghost Form & Hiding": "鬼魂形態與隱藏", "Immunity Providers": "提供免疫", "Minions Summoners": "召喚小兵",
    "Mega Minions Summoners": "召喚巨型小兵", "Minions Counters": "反製小兵", "Minions Boosters": "小兵強化", "Fiends Summoners": "召喚惡魔",
    "Fiends Counters": "反製惡魔", "Counterattackers": "反擊", "Reflectors": "反射", "Bypassers": "繞過", "Targeting Type": "目標類型",
    "Snipers": "狙擊手", "AoE Attackers (Hit-5)": "全體攻擊 (打5)", "AoE Attackers (Hit-3)": "範圍攻擊 (打3)",
    "Chain & Random Attackers": "連鎖與隨機攻擊", "Board Alterers": "改變面板", "Ability Scores Modifiers": "屬性修改",
    "Negative Effects On Self Or Allies": "對自身或友軍負面效果", "Status Effect Conversion": "狀態效果轉換"
};

// --- 语言文本管理 ---
const i18n = {
    cn: {
        metaDescription: "Heroplan是为《帝国与谜题》(Empires & Puzzles)玩家打造的终极英雄资料库。快速查询和比较所有英雄的详细数据、特殊技能、家族加成和攻略信息。",
        seoHeading: "《帝国与谜题》一站式英雄资料库与玩家工具箱",
        seoPara1: "欢迎使用由 <strong>Heroplan.io</strong> 驱动的《帝国与谜题》(Empires & Puzzles) 终极英雄资料与攻略平台。我们提供最新、最全面的<strong>英雄数据</strong>，包括星级、颜色、法速、职业、家族、起源及所有<strong>服装</strong>信息。",
        seoPara2: "本站的独特之处在于其强大的交互功能：使用我们强大的筛选系统，您不仅能按名称、来源等基本属性查找英雄，更能通过<strong>特殊技能文本</strong>、<strong>被动技能描述</strong>及精细的技能分类进行高级检索。独一无二的<strong>属性计算器</strong>，允许您实时查看英雄在不同极限突破（LB1/LB2）和天赋（+20/+25）等级下的确切战力、攻击、防御及生命值，为您的英雄成长规划提供数据支持。",
        seoPara3: "除了英雄数据库，我们还集成了多种实用工具来提升您的游戏体验：使用创新的【<strong>聊天模拟器</strong>】，您可以轻松制作带自定义颜色和游戏表情的聊天内容并一键复制；查阅我们详尽的【<strong>材料出处指南</strong>】和【<strong>通缉任务</strong>】速查表，高效定位资源，优化您的游戏攻略。您可以收藏您喜爱的英雄组合，并通过链接将您的<strong>收藏列表</strong>分享给盟友。平台完整支持简/繁中文和英文，并提供日/夜间模式切换功能。",
        pageTitle: "帝国与谜题英雄资料库 | Heroplan",
        headerTitle: "Heroplan英雄资料库", poweredBy: "由", driven: "驱动",
        sponsoredBy: "赞助", translatedBy: "译者制作",
        "skillClassificationBy": "技能类别原作者:",
        "sourceCite": "来源:",
        "aetherDataSource": "突破/天赋数据:", footerInfo: "英雄数据持续更新 | 简繁体中文版",
        filterHeroes: "筛选英雄", standardFilters: "标准筛选", nameLabel: "名称:", avatarLabel: "头像", namePlaceholder: "输入英雄名称", costumeTypeLabel: "服装类型:",
        starLabel: "星级:", colorLabel: "颜色:", speedLabel: "法速:", classLabel: "职业:", familyLabel: "家族:",
        sourceLabel: "起源:", aetherPowerLabel: "以太力量:", showEventNameLabel: "显示活动名称", filterHeroes: "筛选英雄",
        filterScopeLabel: "筛选范围:", filterScope_all: "全部",
        filterScope_hero: "英雄",
        filterScope_skin: "服装",
        filterScope_favorites: "收藏", clearSelection: "清空选择", advancedFilters: "高级筛选",
        skillTypeSourceLabel: "技能类别来源:", sourceBoth: "全部", sourceHeroplan: "Heroplan.io", sourceNynaeve: "By Nynaeve",
        skillTypeLabel: "特殊技能类别:", skillTypePlaceholder: "例如：增益,异常,治疗", skillTextLabel: "特殊技能文本:",
        passiveSkillLabel: "被动技能文本:", filterBy: "筛选:", all: "全部", hero: "英雄", skin: "服装", favorites: "收藏",
        oneClickMaxEventLabel: "一键满级活动日期:", purchaseCostumeEventLabel: "购买服装活动日期:",
        filterButtonLabel: "筛选",
        minPower: "战力", minAttack: "攻击", minDefense: "防御", minHealth: "生命", resetFilters: "重置筛选",
        shareFavorites: "分享收藏", openFavorites: "打开收藏", shareFavoritesCopied: "列表已复制!",
        footerGameName: "《帝国与谜题》", footerPlatform: "英雄数据查询平台",
        footerCredit: "© 2025 heroplan.github.io | 非官方资料站",
        resultsCountTextFiltered: (count) => `筛选列表中有 ${count} 位英雄`,
        resultsCountTextUnfiltered: (count) => `显示列表中有 ${count} 位英雄`,
        resultsReset: "重置",
        noResults: "没有找到匹配的英雄", modalHeroDetails: "ℹ️ 英雄详情",
        closeBtnTitle: "关闭", modalOrigin: "起源", modalCoreStats: "📊 核心属性",
        limitBreakSetting: "突破设置:",
        noLimitBreak: "无突破",
        lb1: "🔼LB1",
        lb2: "⏫LB2",
        talentSetting: "天赋设置:",
        noTalent: "无天赋",
        talent20: "20 天赋",
        talent25: "25 天赋",
        prioritySetting: "天赋优先级:",
        attackPriority: "攻击 > 防御 > 生命",
        defensePriority: "防御 > 生命 > 攻击",
        attackPriority2: "攻击 > 生命 > 防御",
        healthPriority: "生命 > 防御 > 攻击",
        manaPriorityLabel: "法速节点:",
        manaPriorityToggle: "优先选择",
        modalTalentSettingsTitle: "突破与天赋设置",
        talentTreeTitle: "职业天赋树", modalSettings: "设置", defaultStatSettingsTitle: "突破天赋设置", toggleCollapse: "点击折叠/展开", modalSkillDetails: "📖 技能详情",
        modalSkillName: "📄 名称:", modalSpeed: "⌛ 法速:", modalSkillType: "🏷️ 技能类型:",
        modalSpecialSkill: "✨ 特殊技能:", modalPassiveSkill: "🧿 被动技能:",
        modalFamilyBonus: (family) => `👪 家族加成 (${family}):`, modalSkin: "服装:", none: "无", detailsCloseBtn: "关闭",
        shareButtonTitle: "分享", favoriteButtonTitle: "收藏", favColumnHeader: "☆",
        favHeaderTitle: "一键收藏/取消全部",
        confirmFavoriteAll: "您确定要收藏当前列表中的所有英雄吗？",
        confirmUnfavoriteAll: "您确定要取消收藏当前列表中的所有英雄吗？",
        filterHelpTitle: "高级筛选语法说明",
        filterHelpIntro: "在“特殊技能/被动技能”输入框中，您可使用以下操作符构建复杂查询：",
        filterHelpOr: "<li><strong>| (或):</strong> 查找包含多个关键词中任意一个的英雄。例如: <code>治疗|复活</code> 会找到技能中包含“治疗”或“复活”的英雄。</li>",
        filterHelpAnd: "<li><strong>空格 (与):</strong> 查找必须同时包含多个关键词的英雄。例如: <code>攻击 提高</code> 会找到技能中同时包含“攻击”和“提升”的英雄。</li>",
        filterHelpNot: "<li><strong>! (非):</strong> 排除包含特定关键词的英雄。例如: <code>!治疗</code> 会找到所有技能中不含“治疗”的英雄。</li>",
        filterHelpGroup: "<li><strong>() (分组/单句匹配):</strong> 使用括号进行复杂组合时，<strong style='color: var(--md-sys-color-error);'>强制在单句技能描述中进行匹配</strong>。例如: <code>(抵抗 治疗)</code> 会查找在单句中同时包含“抵抗”和“治疗”的英雄。</li>",
        filterHelpExact: "<li><strong>[] (完全匹配):</strong> 使用方括号可<strong style='color: var(--md-sys-color-error);'>强制单条技能类别完全匹配</strong>。例如: <code>[净化]</code> 会精确寻找技能类别为“净化”的英雄，而不会匹配到“高级净化”或“净化格挡者”。</li>",
        filterHelpExample: "<li><strong>综合示例:</strong> <code>((免疫|反弹) 增益)</code> 会查找能提供免疫或反弹增益的英雄（且所有条件需在同一句描述中满足）。</li>",
        skillTypeHelpTitle: "技能类别来源说明",
        skillTypeHelpContent: `<p>您可以选择不同的技能分类标签来源进行筛选：</p><ul><li><strong>Heroplan.io:</strong> 数据来自 <a href="https://heroplan.io/" target="_blank" rel="noopener noreferrer">Heroplan.io</a> 网站。</li><li><strong>By Nynaeve:</strong> 数据来自 <a href="http://www.theravenscave.com/" target="_blank" rel="noopener noreferrer">www.theravenscave.com</a>，经过AI补全和人工审核。</li><li><strong>全部:</strong> 同时搜索以上两种来源的标签。</li></ul><p>各类别的详细定义，请参考源网站。</p>`,
        noFavoritesToShare: "没有可分享的收藏。",
        copyLinkFailed: "复制链接失败，请尝试手动复制。",
        wantedMissionTableTitle: "通缉任务表",
        farmingGuideTableTitle: "材料出处指南",
        questHeaderDaily: "日常",
        questHeaderRed: "红",
        questHeaderGreen: "绿",
        questHeaderBlue: "蓝",
        questHeaderPurple: "紫",
        questHeaderYellow: "黄",
        toggleThemeTitle: "切换日间/夜间模式",
        toggleLanguageTitle: "切换语言",
        showWantedMissionTitle: "显示通缉任务表",
        openFiltersTitle: "打开筛选",
        calendarTitle: "查看活动日历",
        filterSyntaxTitle: "筛选语法说明",
        skillTypeSourceHelpTitle: "技能类别来源说明",
        returnToList: "返回",
        teamDisplayTitle: "阵容配置",
        noTeamTags: "队伍中暂无技能标签",
        saveTeamBtn: "保存队伍",
        shareTeamListBtn: "分享列表",
        savedTeamsTitle: "已存队伍",
        promptTeamName: "为您的队伍命名:",
        teamNameRequired: "队伍名称不能为空。",
        noHeroesInTeam: "队伍中没有英雄可供保存。",
        removeTeamBtnTitle: "移除此队伍",
        noSavedTeams: "没有已保存的队伍。",
        confirmRemoveTeam: (name) => `您确定要移除队伍 "${name}" 吗？`,
        shareTeamListCopied: "链接已复制!",
        noTeamsToShare: "没有可分享的队伍。", 
        clearTeamBtn: "清空阵容",
        confirmClearTeam: "您确定要清空当前阵容吗？所有未保存的更改都将丢失。",
        importSuccess: (teamName) => `队伍 "${teamName}" 已成功导入！`,
        importConfirmOverwrite: (teamName) => `队伍 "${teamName}" 已存在。您想覆盖它吗？`,
        importEnterNewName: (teamName) => `队伍 "${teamName}" 已存在。请输入一个新的名称以导入：`,
        importedBtn: "已导入",
        importTeamBtn: "导入",
        teamImportedBtn: "已导入",
        sharedTeamsTitle: "分享的队伍", 
        myTeamsTab: "我的队伍",
        sharedTeamsTab: "分享的队伍",
        summaryTagsTitle: "技能标签汇总",
        // --- 聊天模拟器新增文本 ---
        showChatSimulatorTitle: "聊天模拟器",
        chatSimulatorTitle: "聊天模拟器",
        chatPanelTitleColors: "选择颜色",
        chatPanelTitleEmojis: "选择表情",
        chatFavoriteColorBtn: "⭐",
        chatFavoriteColorsTitle: "已收藏的颜色",
        chatPanelTitleIO: "输入与预览",
        chatInsertColorBtn: "插入",
        chatCopyBtn: "复制内容",
        chatCopied: "已复制!",
        talentTerms: {
            '攻击': '攻击',
            '防御': '防御',
            '生命': '生命',
            '法力': '法力',
            '治疗': '治疗',
            '暴击': '暴击',
            '游侠天赋': '游侠天赋', '战士天赋': '战士天赋', '圣骑天赋': '圣骑天赋',
            '野蛮人天赋': '野蛮人天赋', '牧师天赋': '牧师天赋', '德鲁伊天赋': '德鲁伊天赋',
            '僧侣天赋': '僧侣天赋', '盗贼天赋': '盗贼天赋', '术士天赋': '术士天赋', '巫师天赋': '巫师天赋',
            '游侠终极天赋': '游侠终极天赋', '战士终极天赋': '战士终极天赋', '圣骑士终极天赋': '圣骑士终极天赋',
            '野蛮人终极天赋': '野蛮人终极天赋', '牧师终极天赋': '牧师终极天赋', '德鲁伊终极天赋': '德鲁伊终极天赋',
            '僧侣终极天赋': '僧侣终极天赋', '盗贼终极天赋': '盗贼终极天赋', '术士终极天赋': '术士终极天赋', '巫师终极天赋': '巫师终极天赋',
        },
        bonusAndCostTitle: "天赋加成与消耗",
        attackBonusLabel: "攻击:",
        defenseBonusLabel: "防御:",
        healthBonusLabel: "生命:",
        manaBonusLabel: "法力:",
        healingBonusLabel: "治疗:",
        critBonusLabel: "暴击:",
        noBonusLabel: "未获得任何属性加成",
        emblemCostLabel: "纹章:",
        foodCostLabel: "食物:",
        ironCostLabel: "铁矿:",
        masterEmblemCostLabel: "大师纹章:",
        lbTalentHelpTitle: "突破与天赋设置说明",
        lbTalentHelpLine1: "突破后属性和天赋升级消耗资源数据均来自 <a href='https://bbcamp.info' target='_blank' rel='noopener noreferrer'>https://bbcamp.info</a><br><br>突破和天赋带来的属性加成只能展示对应的战力、攻击、防御和生命值，无法展示加成后的技能持续伤害和效果，技能相关具体数值请在游戏中查看。",
        lbTalentHelpLine2: "法力优先则以法力为最优先级，必定升级法力的天赋。",


    },
    tc: {
        metaDescription: "Heroplan是為《帝國與謎題》(Empires & Puzzles)玩家打造的終極英雄資料庫。快速查詢和比較所有英雄的詳細數據、特殊技能、家族加成和攻略資訊。",
        seoHeading: "《帝國與謎題》一站式英雄資料庫與玩家工具箱",
        seoPara1: "歡迎使用由 <strong>Heroplan.io</strong> 驅動的《帝國與謎題》(Empires & Puzzles) 終極英雄資料與攻略平台。我們提供最新、最全面的<strong>英雄數據</strong>，包括星級、顏色、法速、職業、家族、起源及所有<strong>服裝</strong>資訊。",
        seoPara2: "本站的獨特之處在於其強大的互動功能：使用我們強大的篩選系統，您不僅能按名稱、來源等基本屬性查找英雄，更能透過<strong>特殊技能文本</strong>、<strong>被動技能描述</strong>及精細的技能分類進行進階檢索。獨一無二的<strong>屬性計算器</strong>，允許您即時查看英雄在不同極限突破（LB1/LB2）和天賦（+20/+25）等級下的確切戰力、攻擊、防禦及生命值，為您的英雄成長規劃提供數據支援。",
        seoPara3: "除了英雄資料庫，我們還整合了多種實用工具來提升您的遊戲體驗：使用創新的【<strong>聊天模擬器</strong>】，您可以輕鬆製作帶自訂顏色和遊戲表情的聊天內容並一鍵複製；查閱我們詳盡的【<strong>材料出處指南</strong>】和【<strong>通緝任務</strong>】速查表，高效定位資源，最佳化您的遊戲攻略。您可以收藏您喜愛的英雄組合，並透過連結將您的<strong>收藏列表</strong>分享給盟友。平台完整支援簡/繁中文和英文，並提供日/夜間模式切換功能。",
        pageTitle: "帝國與謎題英雄資料庫 | Heroplan",
        headerTitle: "Heroplan英雄資料庫", poweredBy: "由", driven: "驅動",
        sponsoredBy: "贊助", translatedBy: "譯者製作",
        "skillClassificationBy": "技能類別原作者:",
        "sourceCite": "來源:",
        "aetherDataSource": "突破/天賦數據:", footerInfo: "英雄數據持續更新 | 簡繁中文版",
        filterHeroes: "篩選英雄", standardFilters: "標準篩選", nameLabel: "名稱:", avatarLabel: "頭像", namePlaceholder: "輸入英雄名稱", costumeTypeLabel: "服裝類型:",
        starLabel: "星級:", colorLabel: "顏色:", speedLabel: "法速:", classLabel: "職業:", familyLabel: "家族:",
        sourceLabel: "起源:", aetherPowerLabel: "以太力量:", showEventNameLabel: "顯示活動名稱", filterHeroes: "筛选英雄", 
        filterScopeLabel: "篩選範圍:",
        filterScope_hero: "英雄",
        filterScope_skin: "服裝",
        filterScope_favorites: "收藏", clearSelection: "清空選擇", advancedFilters: "高級篩選",
        skillTypeSourceLabel: "技能類別來源:", sourceBoth: "全部", sourceHeroplan: "Heroplan.io", sourceNynaeve: "By Nynaeve",
        skillTypeLabel: "特殊技能類別:", skillTypePlaceholder: "例如：增益,異常,治療", skillTextLabel: "特殊技能文本:",
        passiveSkillLabel: "被動技能文本:", filterBy: "篩選:", all: "全部", hero: "英雄", skin: "服裝", favorites: "收藏",
        oneClickMaxEventLabel: "一鍵滿級活動日期:", purchaseCostumeEventLabel: "購買服裝活動日期:",
        filterButtonLabel: "篩選",
        minPower: "戰力", minAttack: "攻擊", minDefense: "防禦", minHealth: "生命", resetFilters: "重置篩選",
        shareFavorites: "分享收藏", openFavorites: "打開收藏", shareFavoritesCopied: "列表已複製!",
        footerGameName: "《帝國與謎題》", footerPlatform: "英雄數據查詢平台",
        footerCredit: "© 2025 heroplan.github.io | 非官方資料站",
        resultsCountTextFiltered: (count) => `篩選清單中有 ${count} 位英雄`,
        resultsCountTextUnfiltered: (count) => `顯示清單中有 ${count} 位英雄`,
        resultsReset: "重設",
        noResults: "沒有找到匹配的英雄", modalHeroDetails: "ℹ️ 英雄詳情",
        closeBtnTitle: "關閉", modalOrigin: "起源", modalCoreStats: "📊 核心屬性",
        limitBreakSetting: "突破設置:",
        noLimitBreak: "無突破",
        lb1: "🔼LB1",
        lb2: "⏫LB2",
        talentSetting: "天賦設置:",
        noTalent: "無天賦",
        talent20: "20 天賦",
        talent25: "25 天賦",
        prioritySetting: "天賦優先級:",
        attackPriority: "攻擊 > 防禦 > 生命",
        defensePriority: "防禦 > 生命 > 攻擊",
        attackPriority2: "攻擊 > 生命 > 防禦",
        healthPriority: "生命 > 防禦 > 攻擊",
        manaPriorityLabel: "法速節點:",
        manaPriorityToggle: "優先選擇",
        modalTalentSettingsTitle: "突破與天賦設置",
        talentTreeTitle: "職業天賦樹", modalSettings: "設置", defaultStatSettingsTitle: "突破天賦設置", toggleCollapse: "點擊折疊/展開", modalSkillDetails: "📖 技能詳情",
        modalSkillName: "📄 名稱:", modalSpeed: "⌛ 法速:", modalSkillType: "🏷️ 技能類型:",
        modalSpecialSkill: "✨ 特殊技能:", modalPassiveSkill: "🧿 被動技能:",
        modalFamilyBonus: (family) => `👪 家族加成 (${family}):`, modalSkin: "服裝:", none: "無", detailsCloseBtn: "關閉",
        shareButtonTitle: "分享", favoriteButtonTitle: "收藏", favColumnHeader: "☆",
        favHeaderTitle: "一鍵收藏/取消全部",
        confirmFavoriteAll: "您確定要收藏當前列表中的所有英雄嗎？",
        confirmUnfavoriteAll: "您確定要取消收藏當前列表中的所有英雄嗎？",
        filterHelpTitle: "高級篩選語法說明",
        filterHelpIntro: "在“特殊技能/被動技能”輸入框中，您可使用以下運算子構建複雜查詢：",
        filterHelpOr: "<li><strong>| (或):</strong> 尋找包含多個關鍵詞中任意一個的英雄。例如: <code>治療|復活</code> 會找到技能中包含“治療”或“復活”的英雄。</li>",
        filterHelpAnd: "<li><strong>空格 (與):</strong> 尋找必須同時包含多個關鍵詞的英雄。例如: <code>攻擊 提升</code> 會找到技能中同時包含“攻擊”和“提升”的英雄。</li>",
        filterHelpNot: "<li><strong>! (非):</strong> 排除包含特定關鍵詞的英雄。例如: <code>!治療</code> 會找到所有技能中不含“治療”的英雄。</li>",
        filterHelpGroup: "<li><strong>() (分組/單句匹配):</strong> 使用括號可进行复杂组合，并<strong style='color: var(--md-sys-color-error);'>强制在单句技能描述中进行匹配</strong>。例如: <code>(抵禦 治療)</code> 會精確尋找<strong style='color: var(--md-sys-color-error);'>某一句</strong>技能描述中，同時包含“抵禦”和“治療”的英雄。</li>",
        filterHelpExact: "<li><strong>[] (完全匹配):</strong> 使用方括號可<strong style='color: var(--md-sys-color-error);'>強制單條技能類別完全匹配</strong>。例如: <code>[凈化]</code> 會精確尋找技能類別為“凈化”的英雄，而不會匹配到“高級凈化”或“凈化格擋者”。</li>",
        filterHelpExample: "<li><strong>綜合示例:</strong> <code>((免疫|反射) 增益)</code> 會尋找能提供免疫或反射增益的英雄（且所有條件需在同一句描述中滿足）。</li>",
        skillTypeHelpTitle: "技能類別來源說明",
        skillTypeHelpContent: `<p>您可以選擇不同的技能分類標籤來源進行篩選：</p><ul><li><strong>Heroplan.io:</strong> 資料來自 <a href="https://heroplan.io/" target="_blank" rel="noopener noreferrer">Heroplan.io</a> 網站。</li><li><strong>By Nynaeve:</strong> 資料來自 <a href="http://www.theravenscave.com/" target="_blank" rel="noopener noreferrer">www.theravenscave.com</a>，經過AI補全和人工審核。</li><li><strong>全部:</strong> 同時搜索以上兩種來源的標籤。</li></ul><p>各類別的詳細定義，請參考源網站。</p>`,
        noFavoritesToShare: "沒有可分享的收藏。",
        copyLinkFailed: "複製鏈接失敗，請嘗試手動複製。",
        wantedMissionTableTitle: "通緝任務表",
        farmingGuideTableTitle: "材料出處指南",
        questHeaderDaily: "日常",
        questHeaderRed: "紅",
        questHeaderGreen: "綠",
        questHeaderBlue: "藍",
        questHeaderPurple: "紫",
        questHeaderYellow: "黃",
        toggleThemeTitle: "切換日間/夜間模式",
        toggleLanguageTitle: "切換語言",
        showWantedMissionTitle: "顯示通緝任務表",
        openFiltersTitle: "打開篩選",
        calendarTitle: "查看活動日曆",
        filterSyntaxTitle: "篩選語法說明",
        skillTypeSourceHelpTitle: "技能類別來源說明",
        returnToList: "返回",
        teamDisplayTitle: "陣容配置",
        noTeamTags: "隊伍中暫無技能標籤",
        saveTeamBtn: "儲存隊伍",
        shareTeamListBtn: "分享列表",
        savedTeamsTitle: "已存隊伍",
        promptTeamName: "為您的隊伍命名:",
        teamNameRequired: "隊伍名稱不能為空。",
        noHeroesInTeam: "隊伍中沒有英雄可供儲存。",
        removeTeamBtnTitle: "移除此隊伍",
        noSavedTeams: "沒有已儲存的隊伍。",
        confirmRemoveTeam: (name) => `您確定要移除隊伍 "${name}" 嗎？`,
        shareTeamListCopied: "連結已複製!",
        noTeamsToShare: "沒有可分享的隊伍。",
        clearTeamBtn: "清空陣容",
        confirmClearTeam: "您確定要清空當前陣容嗎？所有未儲存的變更都將遺失。",
        importSuccess: (teamName) => `隊伍 "${teamName}" 已成功匯入！`,
        importConfirmOverwrite: (teamName) => `隊伍 "${teamName}" 已存在。您想覆蓋它嗎？`,
        importTeamBtn: "匯入",
        importEnterNewName: (teamName) => `隊伍 "${teamName}" 已存在。請輸入一個新的名稱以匯入：`,
        importedBtn: "已匯入",
        teamImportedBtn: "已匯入",
        sharedTeamsTitle: "分享的隊伍",
        myTeamsTab: "我的隊伍",
        sharedTeamsTab: "分享的隊伍",
        summaryTagsTitle: "技能標籤匯總",
        // --- 聊天模擬器新增文本 ---
        showChatSimulatorTitle: "聊天模擬器",
        chatSimulatorTitle: "聊天模擬器",
        chatPanelTitleColors: "選擇顏色",
        chatFavoriteColorBtn: "⭐",
        chatFavoriteColorsTitle: "已收藏的顏色",
        chatPanelTitleEmojis: "選擇表情",
        chatPanelTitleIO: "輸入與預覽",
        chatInsertColorBtn: "插入",
        chatCopyBtn: "複製內容",
        chatCopied: "已複製!",
        talentTerms: {
            '攻击': '攻擊',
            '防御': '防禦',
            '生命': '生命',
            '法力': '法力',
            '治疗': '治療',
            '暴击': '暴擊',
            '游侠天赋': '遊俠天賦', '战士天赋': '戰士天賦', '圣骑天赋': '聖騎天賦',
            '野蛮人天赋': '野蠻人天賦', '牧师天赋': '牧師天賦', '德鲁伊天赋': '德魯伊天賦',
            '僧侣天赋': '僧侶天賦', '盗贼天赋': '盜賊天賦', '术士天赋': '術士天賦', '巫师天赋': '巫師天賦',
            '游侠终极天赋': '遊俠終極天賦', '战士终极天赋': '戰士終極天賦', '圣骑士终极天赋': '聖騎士終極天賦',
            '野蛮人终极天赋': '野蠻人終極天賦', '牧师终极天赋': '牧師終極天賦', '德鲁伊终极天赋': '德魯伊終極天賦',
            '僧侣终极天赋': '僧侶終極天賦', '盗贼终极天赋': '盜賊終極天賦', '术士终极天赋': '術士終極天賦', '巫师终极天赋': '巫師終極天賦',
        },
        bonusAndCostTitle: "天賦加成與消耗",
        attackBonusLabel: "攻擊:",
        defenseBonusLabel: "防禦:",
        healthBonusLabel: "生命:",
        manaBonusLabel: "法力:",
        healingBonusLabel: "治療:",
        critBonusLabel: "暴擊:",
        noBonusLabel: "未獲得任何屬性加成",
        emblemCostLabel: "紋章:",
        foodCostLabel: "食物:",
        ironCostLabel: "鐵礦:",
        masterEmblemCostLabel: "大師紋章:",
        lbTalentHelpTitle: "突破與天賦設置說明",
        lbTalentHelpLine1: "突破後屬性和天賦升級消耗資源數據均來自 <a href='https://bbcamp.info' target='_blank' rel='noopener noreferrer'>https://bbcamp.info</a><br><br>突破和天賦帶來的屬性加成只能展示對應的戰力、攻擊、防禦和生命值，無法展示加成後的技能持續傷害和效果，技能相關具體數值請在遊戲中查看。",
        lbTalentHelpLine2: "法力優先則以法力為最優先級,必定升級法力的天賦。",
    },
    en: {
        metaDescription: "The ultimate hero database for Empires & Puzzles players. Quickly search and compare detailed stats, special skills, family bonuses, and strategy guides for all heroes.",
        seoHeading: "Empires & Puzzles One-Stop Hero Database & Player Toolbox",
        seoPara1: "Welcome to the ultimate hero data and strategy platform for Empires & Puzzles, powered by <strong>Heroplan.io</strong>. We provide the latest and most comprehensive <strong>hero data</strong>, including star rating, color, speed, class, family, origin, and all <strong>costume</strong> information.",
        seoPara2: "What makes this site unique are its powerful interactive features: use our robust filtering system to find heroes not only by basic attributes like name and origin, but also through advanced searches of <strong>special skill text</strong>, <strong>passive descriptions</strong>, and detailed skill categories. The one-of-a-kind <strong>Stat Calculator</strong> allows you to see the exact power, attack, defense, and health of a hero at different Limit Break (LB1/LB2) and Talent (+20/+25) levels, providing data-driven support for your hero development plans.",
        seoPara3: "In addition to the hero database, we've integrated several useful tools to enhance your gameplay: use the innovative [<strong>Chat Simulator</strong>] to easily create in-game messages with custom colors and emojis and copy them with one click; consult our detailed [<strong>Farming Guide</strong>] and [<strong>Wanted Missions</strong>] cheat sheet to efficiently locate resources and optimize your strategy. You can save your favorite heroes to a list and share your <strong>Favorites List</strong> with your alliance via a link. The platform fully supports Simplified/Traditional Chinese and English, and includes a Day/Night mode toggle.",
        pageTitle: "Empires & Puzzles Hero Database | Heroplan",
        headerTitle: "Heroplan Hero Database", poweredBy: "Powered by", driven: "",
        sponsoredBy: "Sponsored by", translatedBy: "Developed by",
        "skillClassificationBy": "Special Skill DB by:",
        "sourceCite": "Source:",
        "aetherDataSource": "Aether & Talent Data:", footerInfo: "Hero data is continuously updated | EN/CN Version",
        filterHeroes: "Filter Heroes", standardFilters: "Standard Filters", nameLabel: "Name:", avatarLabel: "Avatar", namePlaceholder: "Enter hero name", costumeTypeLabel: "Costume:",
        starLabel: "Stars:", colorLabel: "Color:", speedLabel: "Speed:", classLabel: "Class:", familyLabel: "Family:",
        sourceLabel: "Origin:", aetherPowerLabel: "Aether Power:", showEventNameLabel: "Show Event Name", filterHeroes: "Filter Heroes",
        filterScopeLabel: "Filter Range:", filterScope_all: "All",
        filterScope_hero: "Hero",
        filterScope_skin: "Costume",
        filterScope_favorites: "Favorites", clearSelection: "Clear Selections", advancedFilters: "Advanced Filters",
        skillTypeSourceLabel: "Type Source:", sourceBoth: "Both", sourceHeroplan: "Heroplan.io", sourceNynaeve: "By Nynaeve",
        skillTypeLabel: "Skill Type:", skillTypePlaceholder: "e.g. buff, ailment, heal", skillTextLabel: "Skill Text:",
        passiveSkillLabel: "Passive Text:", filterBy: "Filter by:", all: "All", hero: "Hero", skin: "Costume", favorites: "Favorites",
        oneClickMaxEventLabel: "Hero Coach:", purchaseCostumeEventLabel: "Visiting Outfitter:",
        filterButtonLabel: "Filter",
        minPower: "Power", minAttack: "Attack", minDefense: "Defense", minHealth: "Health", resetFilters: "Reset Filters",
        shareFavorites: "Share Favorites", openFavorites: "Open Favorites", shareFavoritesCopied: "List Copied!",
        footerGameName: "Empires & Puzzles", footerPlatform: "Hero Data Platform",
        footerCredit: "© 2025 heroplan.github.io | Unofficial Fan Site",
        resultsCountTextFiltered: (count) => `Found ${count} heroes in the filtered list`,
        resultsCountTextUnfiltered: (count) => `Showing ${count} heroes in the list`,
        resultsReset: "Reset",
        noResults: "No matching heroes found", modalHeroDetails: "ℹ️ Hero Details",
        closeBtnTitle: "Close", modalOrigin: "Origin", modalCoreStats: "📊 Core Stats",
        limitBreakSetting: "Limit Break:",
        noLimitBreak: "None",
        lb1: "🔼LB1",
        lb2: "⏫LB2",
        talentSetting: "Talent:",
        noTalent: "No Talents",
        talent20: "20 Talents",
        talent25: "25 Talents",
        prioritySetting: "Talent Priority:",
        attackPriority: "Attack > Defense > Health",
        defensePriority: "Defense > Health > Attack",
        attackPriority2: "Attack > Health > Defense",
        healthPriority: "Health > Defense > Attack",
        manaPriorityLabel: "Mana Node:",
        manaPriorityToggle: "Prioritize",
        modalTalentSettingsTitle: "Limit Break & Talent Settings",
        talentTreeTitle: "Class Talent Tree", modalSettings: "Settings", defaultStatSettingsTitle: "LB Talent Settings", toggleCollapse: "Click to collapse/expand", modalSkillDetails: "📖 Skill Details",
        modalSkillName: "📄 Name:", modalSpeed: "⌛ Speed:", modalSkillType: "🏷️ Skill Type:",
        modalSpecialSkill: "✨ Special Skill:", modalPassiveSkill: "🧿 Passive Skill:",
        modalFamilyBonus: (family) => `👪 Family Bonus (${family}):`, modalSkin: "Costume:", none: "None", detailsCloseBtn: "Close",
        shareButtonTitle: "Share", favoriteButtonTitle: "Favorite", favColumnHeader: "☆",
        favHeaderTitle: "Favorite/Unfavorite All",
        confirmFavoriteAll: "Are you sure you want to favorite all heroes in the current list?",
        confirmUnfavoriteAll: "Are you sure you want to unfavorite all heroes in the current list?",
        filterHelpTitle: "Advanced Filter Syntax",
        filterHelpIntro: "In the 'Skill Text/Passive Text' fields, you can use these operators for complex queries:",
        filterHelpOr: "<li><strong>| (OR):</strong> Finds heroes with any of the specified keywords. E.g., <code>heal|revive</code> finds heroes with 'heal' or 'revive'.</li>",
        filterHelpAnd: "<li><strong>Space (AND):</strong> Finds heroes that must contain all keywords. E.g., <code>attack up</code> finds heroes with both 'attack' and 'up'.</li>",
        filterHelpNot: "<li><strong>! (NOT):</strong> Excludes heroes with a specific keyword. E.g., <code>!heal</code> finds all heroes without 'heal' in their skills.</li>",
        filterHelpGroup: "<li><strong>() (Grouping/Single-Line Match):</strong> Use parentheses for complex grouping and to <strong style='color: var(--md-sys-color-error);'>force matching within a single skill line</strong>. E.g., <code>(resist heal)</code> will precisely find heroes where a <strong style='color: var(--md-sys-color-error);'>single line</strong> of their skill description contains both 'resist' and 'heal'.</li>",
        filterHelpExact: "<li><strong>[] (Exact Match):</strong> Use square brackets to <strong style='color: var(--md-sys-color-error);'>force an exact match on a single skill type line</strong>. E.g., <code>[Cleanse]</code> will find heroes with the exact type 'Cleanse', and not 'Cleansers'.</li>",
        filterHelpExample: "<li><strong>Combined Example:</strong> <code>((immune|reflect) buff)</code> finds heroes who provide an immunity or reflection buff (and all conditions must be met in the same line).</li>",
        skillTypeHelpTitle: "Skill Type Source Explanation",
        skillTypeHelpContent: `<p>You can choose different sources for skill category tags to filter by:</p><ul><li><strong>Heroplan.io:</strong> Data from the <a href="https://heroplan.io/" target="_blank" rel="noopener noreferrer">Heroplan.io</a> website.</li><li><strong>By Nynaeve:</strong> Data from <a href="http://www.theravenscave.com/" target="_blank" rel="noopener noreferrer">www.theravenscave.com</a>, supplemented by AI and manually reviewed.</li><li><strong>Both:</strong> Searches tags from both sources simultaneously.</li></ul><p>For detailed category definitions, please refer to the source websites.</p>`,
        noFavoritesToShare: "No favorites to share.",
        copyLinkFailed: "Failed to copy link. Please try copying it manually.",
        wantedMissionTableTitle: "Wanted Mission Table",
        farmingGuideTableTitle: "Farming Locations Guide",
        questHeaderDaily: "Daily",
        questHeaderRed: "Red",
        questHeaderGreen: "Green",
        questHeaderBlue: "Blue",
        questHeaderPurple: "Purple",
        questHeaderYellow: "Yellow",
        toggleThemeTitle: "Toggle day/night mode",
        toggleLanguageTitle: "Toggle language",
        showWantedMissionTitle: "Show Wanted Mission Table",
        openFiltersTitle: "Open Filters",
        calendarTitle: "View Event Calendar",
        filterSyntaxTitle: "Filter Syntax Help",
        skillTypeSourceHelpTitle: "Skill Type Source Help",
        returnToList: "Return",
        teamDisplayTitle: "Team Configuration",
        noTeamTags: "No skill tags in the team",
        saveTeamBtn: "Save Team",
        shareTeamListBtn: "Share List",
        savedTeamsTitle: "Saved Teams",
        promptTeamName: "Enter a name for your team:",
        teamNameRequired: "Team name cannot be empty.",
        noHeroesInTeam: "No heroes in the team to save.",
        removeTeamBtnTitle: "Remove this team",
        noSavedTeams: "No saved teams.",
        confirmRemoveTeam: (name) => `Are you sure you want to remove the team "${name}"?`,
        shareTeamListCopied: "Link copied!",
        noTeamsToShare: "No teams to share.",
        clearTeamBtn: "Clear Team",
        confirmClearTeam: "Are you sure you want to clear the current team? All unsaved changes will be lost.",
        importSuccess: (teamName) => `Team "${teamName}" imported successfully!`,
        importConfirmOverwrite: (teamName) => `Team "${teamName}" already exists. Overwrite it?`,
        importTeamBtn: "Import",
        importEnterNewName: (teamName) => `Team "${teamName}" already exists. Please enter a new name to import:`,
        importedBtn: "Imported",
        teamImportedBtn: "Imported",
        sharedTeamsTitle: "Shared Teams",
        myTeamsTab: "My Teams",
        sharedTeamsTab: "Shared Teams",
        summaryTagsTitle: "Skill Tags Summary",
        // --- Chat Simulator New Texts ---
        showChatSimulatorTitle: "Chat Simulator",
        chatSimulatorTitle: "Chat Simulator",
        chatPanelTitleColors: "Select Color",
        chatFavoriteColorBtn: "⭐",
        chatFavoriteColorsTitle: "Favorite Colors",
        chatPanelTitleEmojis: "Select Emojis",
        chatPanelTitleIO: "Input & Preview",
        chatInsertColorBtn: "Add",
        chatCopyBtn: "Copy Content",
        chatCopied: "Copied!",
        talentTerms: {
            '攻击': 'Attack',
            '防御': 'Defense',
            '生命': 'Health',
            '法力': 'Mana',
            '治疗': 'Healing',
            '暴击': 'Critical',
            '游侠天赋': 'Ranger Talent', '战士天赋': 'Fighter Talent', '圣骑天赋': 'Paladin Talent',
            '野蛮人天赋': 'Barbarian Talent', '牧师天赋': 'Cleric Talent', '德鲁伊天赋': 'Druid Talent',
            '僧侣天赋': 'Monk Talent', '盗贼天赋': 'Rogue Talent', '术士天赋': 'Sorcerer Talent', '巫师天赋': 'Wizard Talent',
            '游侠终极天赋': 'Ranger Ultimate Talent', '战士终极天赋': 'Fighter Ultimate Talent', '圣骑士终极天赋': 'Paladin Ultimate Talent',
            '野蛮人终极天赋': 'Barbarian Ultimate Talent', '牧师终极天赋': 'Cleric Ultimate Talent', '德鲁伊终极天赋': 'Druid Ultimate Talent',
            '僧侣终极天赋': 'Monk Ultimate Talent', '盗贼终极天赋': 'Rogue Ultimate Talent', '术士终极天赋': 'Sorcerer Ultimate Talent', '巫师终极天赋': 'Wizard Ultimate Talent',
        },
        bonusAndCostTitle: "Talent Bonuses & Costs",
        attackBonusLabel: "Attack:",
        defenseBonusLabel: "Defense:",
        healthBonusLabel: "Health:",
        manaBonusLabel: "Mana:",
        healingBonusLabel: "Healing:",
        critBonusLabel: "Critical:",
        noBonusLabel: "No attribute bonuses gained",
        emblemCostLabel: "Emblems:",
        foodCostLabel: "Food:",
        ironCostLabel: "Iron:",
        masterEmblemCostLabel: "Master Emblems:",
        lbTalentHelpTitle: "Limit Break & Talent Settings Help",
        lbTalentHelpLine1: "Data for post-limit break stats and talent upgrade costs are from <a href='https://bbcamp.info' target='_blank' rel='noopener noreferrer'>https://bbcamp.info</a><br><br>The stat bonuses from limit breaks and talents can only display the corresponding Power, Attack, Defense, and Health. They cannot show damage over time or skill effects after bonuses. Please check in-game for specific skill-related values.",
        lbTalentHelpLine2: "Mana Priority gives mana nodes the highest priority, ensuring they are always selected in the talent path.",
    }
}; 